/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Rumah_Sakit;

import javax.swing.JFrame;

public class ActionMenu extends JFrame {
    private String role;
    private DataManager manager;
    /**
     * Creates new form ActionMenu
     */
    public ActionMenu(DataManager manager, String role) {
        this.role = role;
        this.manager = manager;
        initComponents();
        if(manager.is_admin()){
            jbuttonUser.setEnabled(true);
            jbuttonPatient.setEnabled(true);
            jbuttonAppointment.setEnabled(true);
            jbuttonMedicine.setEnabled(true);
            jLabelportal.setText("ADMIN PORTAL");
        }
        if(manager.is_staff()){
            jbuttonPatient.setEnabled(true);
            jbuttonAppointment.setEnabled(true);
            jLabelportal.setText("STAFF PORTAL");
        }
        if(manager.is_doctor()){
            jbuttonAppointment.setEnabled(true);
            jLabelportal.setText("DOCTOR PORTAL");
        }
        if(manager.is_pharmacist()){
            jbuttonMedicine.setEnabled(true);
            jbuttonAppointment.setEnabled(true);
            jLabelportal.setText("PHARMACIST PORTAL");
        }
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jPanelbiru = new javax.swing.JPanel();
        jLabelhexa1 = new javax.swing.JLabel();
        jLabelportal = new javax.swing.JLabel();
        jLabelhexa3 = new javax.swing.JLabel();
        jbuttonUser = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jbuttonPatient = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jbuttonAppointment = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jbuttonMedicine = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButtonexit = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rumah_Sakit/assets/Background fix.jpg"))); // NOI18N
        jLabel10.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelbiru.setBackground(new java.awt.Color(34, 167, 240));

        jLabelhexa1.setBackground(new java.awt.Color(228, 241, 254));
        jLabelhexa1.setFont(new java.awt.Font("Champagne & Limousines", 0, 36)); // NOI18N
        jLabelhexa1.setForeground(new java.awt.Color(240, 240, 240));
        jLabelhexa1.setText("to");

        jLabelportal.setBackground(new java.awt.Color(228, 241, 254));
        jLabelportal.setFont(new java.awt.Font("Champagne & Limousines", 0, 36)); // NOI18N
        jLabelportal.setForeground(new java.awt.Color(240, 240, 240));
        jLabelportal.setText("ADMIN PORTAL");

        jLabelhexa3.setBackground(new java.awt.Color(228, 241, 254));
        jLabelhexa3.setFont(new java.awt.Font("Champagne & Limousines", 1, 48)); // NOI18N
        jLabelhexa3.setForeground(new java.awt.Color(240, 240, 240));
        jLabelhexa3.setText("WELCOME");

        javax.swing.GroupLayout jPanelbiruLayout = new javax.swing.GroupLayout(jPanelbiru);
        jPanelbiru.setLayout(jPanelbiruLayout);
        jPanelbiruLayout.setHorizontalGroup(
            jPanelbiruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelbiruLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelbiruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelportal)
                    .addGroup(jPanelbiruLayout.createSequentialGroup()
                        .addComponent(jLabelhexa3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelhexa1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelbiruLayout.setVerticalGroup(
            jPanelbiruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelbiruLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(jPanelbiruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelhexa3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelhexa1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelportal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(210, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelbiru, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 310, 460));

        jbuttonUser.setBackground(new java.awt.Color(228, 241, 254));
        jbuttonUser.setFont(new java.awt.Font("Gill Sans MT", 2, 18)); // NOI18N
        jbuttonUser.setForeground(new java.awt.Color(34, 167, 240));
        jbuttonUser.setText("User");
        jbuttonUser.setEnabled(false);
        jbuttonUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonUserActionPerformed(evt);
            }
        });
        getContentPane().add(jbuttonUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 120, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rumah_Sakit/assets/Admin-compress2.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 110, -1));

        jbuttonPatient.setBackground(new java.awt.Color(228, 241, 254));
        jbuttonPatient.setFont(new java.awt.Font("Gill Sans MT", 2, 18)); // NOI18N
        jbuttonPatient.setForeground(new java.awt.Color(34, 167, 240));
        jbuttonPatient.setText("Patient");
        jbuttonPatient.setEnabled(false);
        jbuttonPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonPatientActionPerformed(evt);
            }
        });
        getContentPane().add(jbuttonPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 120, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rumah_Sakit/assets/Patient-compress2.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        jbuttonAppointment.setBackground(new java.awt.Color(228, 241, 254));
        jbuttonAppointment.setFont(new java.awt.Font("Gill Sans MT", 2, 18)); // NOI18N
        jbuttonAppointment.setForeground(new java.awt.Color(34, 167, 240));
        jbuttonAppointment.setText("Appointment");
        jbuttonAppointment.setEnabled(false);
        jbuttonAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonAppointmentActionPerformed(evt);
            }
        });
        getContentPane().add(jbuttonAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 120, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rumah_Sakit/assets/Appointment-compress2.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, -1, -1));

        jbuttonMedicine.setBackground(new java.awt.Color(228, 241, 254));
        jbuttonMedicine.setFont(new java.awt.Font("Gill Sans MT", 2, 18)); // NOI18N
        jbuttonMedicine.setForeground(new java.awt.Color(34, 167, 240));
        jbuttonMedicine.setText("Medicine");
        jbuttonMedicine.setEnabled(false);
        jbuttonMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonMedicineActionPerformed(evt);
            }
        });
        getContentPane().add(jbuttonMedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 120, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rumah_Sakit/assets/Medicine-compress2.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, -1, -1));

        jButtonexit.setBackground(new java.awt.Color(242, 38, 19));
        jButtonexit.setFont(new java.awt.Font("Gill Sans MT", 2, 12)); // NOI18N
        jButtonexit.setText("LOGOUT");
        jButtonexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonexitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 90, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rumah_Sakit/assets/Background fix.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbuttonUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonUserActionPerformed

            Admin a = new Admin(manager);
            a.setTitle("HeXa Hospital Management System");
            a.setSize(800,540);
            a.setLocationRelativeTo(null);
            a.setVisible(true);     
    }//GEN-LAST:event_jbuttonUserActionPerformed

    private void jbuttonPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonPatientActionPerformed
        Patient p = new Patient(manager);
        p.setTitle("HeXa Hospital Management System");
        p.setSize(800,540);
        p.setLocationRelativeTo(null);
        p.setVisible(true); 
    }//GEN-LAST:event_jbuttonPatientActionPerformed

    private void jbuttonAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonAppointmentActionPerformed
       Appointment ap = new Appointment(manager);
        ap.setTitle("HeXa Hospital Management System");
        ap.setSize(800,540);
        ap.setLocationRelativeTo(null);
        ap.setVisible(true);  
    }//GEN-LAST:event_jbuttonAppointmentActionPerformed

    private void jbuttonMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonMedicineActionPerformed
        Medicine m = new Medicine(manager);
        m.setTitle("HeXa Hospital Management System");
        m.setSize(800,540);
        m.setLocationRelativeTo(null);
        m.setVisible(true); 
    }//GEN-LAST:event_jbuttonMedicineActionPerformed

    private void jButtonexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonexitActionPerformed
        Menu_Utama mu = new Menu_Utama();
        mu.setTitle("HeXa Hospital Management System");
        mu.setSize(800,540);
        mu.setLocationRelativeTo(null);
        mu.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        mu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActionMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActionMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActionMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActionMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {                                         
                ActionMenu am = new ActionMenu(null, "patient");
                am.setTitle("HeXa Hospital Management System");
                am.setSize(800,540);
                am.setLocationRelativeTo(null);
                am.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                am.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonexit;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelhexa1;
    private javax.swing.JLabel jLabelhexa3;
    private javax.swing.JLabel jLabelportal;
    private javax.swing.JPanel jPanelbiru;
    private javax.swing.JButton jbuttonAppointment;
    private javax.swing.JButton jbuttonMedicine;
    private javax.swing.JButton jbuttonPatient;
    private javax.swing.JButton jbuttonUser;
    // End of variables declaration//GEN-END:variables
}
