/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Rumah_Sakit;

import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JFrame;

public class AppointmentForm extends javax.swing.JFrame {
    private DataManager manager;
    private int appointment_id;
    private Appointment parent = new Appointment(null);
    /**
     * Creates new form AdminForm
     */
    public AppointmentForm(int appointment_id, DataManager manager, Appointment parent) {
        initComponents();
        initDatas(appointment_id, manager);
        this.parent = parent;
    }

    public void initDatas(int appointment_id, DataManager manager){       
        this.manager = manager;
        this.appointment_id = appointment_id;
        
        ArrayList<Object> patients = manager.get_patients();
        ArrayList<Object> doctors = manager.get_doctors();

        for(int i=0; i<patients.size(); i++){
            patientChoice.addItem(((Object[]) patients.get(i))[1].toString());
        }  
        for(int i=0; i<doctors.size(); i++){
            doctorChoice.addItem(((Object[]) doctors.get(i))[1].toString());
        }  
            
        if(manager==null){
            jbuttonsave.setEnabled(false);
        }    
        
        if(appointment_id>=0 && manager!=null){
            Object[] appointment = manager.get_appointment(appointment_id);
            
            String[] patient_choice = new String[patientChoice.getItemCount()];
            for(int i=0; i<patientChoice.getItemCount(); i++){
                patient_choice[i] = patientChoice.getItemAt(i);
            }
            patientChoice.setSelectedIndex(Arrays.asList(patient_choice).indexOf(appointment[2]));
            
            String[] doctor_choice = new String[doctorChoice.getItemCount()];
            for(int i=0; i<doctorChoice.getItemCount(); i++){
                doctor_choice[i] = doctorChoice.getItemAt(i);
            }
            doctorChoice.setSelectedIndex(Arrays.asList(doctor_choice).indexOf(appointment[1]));
            
            complaintField.setText((String) appointment[3]);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelbiru = new javax.swing.JPanel();
        jLabelhexa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbuttonclose = new javax.swing.JButton();
        jbuttonsave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        complaintField = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        doctorChoice = new javax.swing.JComboBox<>();
        patientChoice = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelbiru.setBackground(new java.awt.Color(34, 167, 240));

        jLabelhexa.setBackground(new java.awt.Color(228, 241, 254));
        jLabelhexa.setFont(new java.awt.Font("Trajan Pro", 0, 24)); // NOI18N
        jLabelhexa.setForeground(new java.awt.Color(240, 240, 240));
        jLabelhexa.setText("ADD MEDICINE HEXA HOSPITAL");

        javax.swing.GroupLayout jPanelbiruLayout = new javax.swing.GroupLayout(jPanelbiru);
        jPanelbiru.setLayout(jPanelbiruLayout);
        jPanelbiruLayout.setHorizontalGroup(
            jPanelbiruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelbiruLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelhexa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelbiruLayout.setVerticalGroup(
            jPanelbiruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelbiruLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabelhexa, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        getContentPane().add(jPanelbiru, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 16, 450, -1));

        jLabel1.setText("Patient:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel2.setText("Doctor:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        jLabel3.setText("Complaint:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 176, -1, -1));

        jbuttonclose.setBackground(new java.awt.Color(228, 241, 254));
        jbuttonclose.setFont(new java.awt.Font("Gill Sans MT", 2, 18)); // NOI18N
        jbuttonclose.setForeground(new java.awt.Color(34, 167, 240));
        jbuttonclose.setText("Close");
        jbuttonclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttoncloseActionPerformed(evt);
            }
        });
        getContentPane().add(jbuttonclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 120, 40));

        jbuttonsave.setBackground(new java.awt.Color(228, 241, 254));
        jbuttonsave.setFont(new java.awt.Font("Gill Sans MT", 2, 18)); // NOI18N
        jbuttonsave.setForeground(new java.awt.Color(34, 167, 240));
        jbuttonsave.setText("Save");
        jbuttonsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonsaveActionPerformed(evt);
            }
        });
        getContentPane().add(jbuttonsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 120, 40));

        complaintField.setColumns(20);
        complaintField.setRows(5);
        jScrollPane1.setViewportView(complaintField);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 530, 150));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        getContentPane().add(doctorChoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 270, -1));

        getContentPane().add(patientChoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 270, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbuttoncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttoncloseActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jbuttoncloseActionPerformed

    private void jbuttonsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonsaveActionPerformed
        String patient = patientChoice.getSelectedItem().toString().toLowerCase();
        String doctor = doctorChoice.getSelectedItem().toString().toLowerCase();
        String complaint = complaintField.getText();
        String data[] = {patient, doctor, complaint};        // TODO add your handling code here:
        
        manager.save_appointment(appointment_id, data);
        parent.refreshTable();
        dispose();
    }//GEN-LAST:event_jbuttonsaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppointmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppointmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppointmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppointmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AppointmentForm af = new AppointmentForm(-1, null, new Appointment(null));
                af.setTitle("HeXa Hospital Management System");
                af.setSize(564, 620);
                af.setLocationRelativeTo(null);
                af.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                af.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea complaintField;
    private javax.swing.JComboBox<String> doctorChoice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelhexa;
    private javax.swing.JPanel jPanelbiru;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbuttonclose;
    private javax.swing.JButton jbuttonsave;
    private javax.swing.JComboBox<String> patientChoice;
    // End of variables declaration//GEN-END:variables
}
