/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Rumah_Sakit;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Appointment extends JFrame {

    private DataManager manager;
    private int selected_row = -1;
    private ArrayList<Integer> ids = new ArrayList<Integer>();
    /**
     * Creates new form Medicine
     */
    public Appointment(DataManager manager) {
        initComponents();
        if(manager!=null){
            if(manager.is_doctor() || manager.is_pharmacist()){
                newButton.setEnabled(false);
            }
        }
        initDatas(manager);
    }
    
    public void initDatas(DataManager manager){
        this.manager = manager;
        if(manager!=null){
            manager.get_patients();
        }
        refreshTable();
        proccessButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelbiru = new javax.swing.JPanel();
        jLabelhexa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        proccessButton = new javax.swing.JButton();
        jButtonexit = new javax.swing.JButton();
        jButtonexit1 = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        newButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelbiru.setBackground(new java.awt.Color(34, 167, 240));

        jLabelhexa.setBackground(new java.awt.Color(228, 241, 254));
        jLabelhexa.setFont(new java.awt.Font("Trajan Pro", 0, 24)); // NOI18N
        jLabelhexa.setForeground(new java.awt.Color(240, 240, 240));
        jLabelhexa.setText("APPOINTMENT HEXA HOSPITAL");

        javax.swing.GroupLayout jPanelbiruLayout = new javax.swing.GroupLayout(jPanelbiru);
        jPanelbiru.setLayout(jPanelbiruLayout);
        jPanelbiruLayout.setHorizontalGroup(
            jPanelbiruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelbiruLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabelhexa, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );
        jPanelbiruLayout.setVerticalGroup(
            jPanelbiruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelhexa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelbiru, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 16, 773, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Doctor", "Patient", "Complain ", "Diagnose"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 118, 773, 317));

        proccessButton.setBackground(new java.awt.Color(228, 241, 254));
        proccessButton.setFont(new java.awt.Font("Gill Sans MT", 2, 18)); // NOI18N
        proccessButton.setForeground(new java.awt.Color(34, 167, 240));
        proccessButton.setText("Proccess");
        proccessButton.setEnabled(false);
        proccessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proccessButtonActionPerformed(evt);
            }
        });
        getContentPane().add(proccessButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 120, 40));

        jButtonexit.setBackground(new java.awt.Color(242, 38, 19));
        jButtonexit.setFont(new java.awt.Font("Gill Sans MT", 2, 12)); // NOI18N
        jButtonexit.setText("LOGOUT");
        jButtonexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonexitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 446, 81, 42));

        jButtonexit1.setBackground(new java.awt.Color(0, 153, 153));
        jButtonexit1.setFont(new java.awt.Font("Gill Sans MT", 2, 12)); // NOI18N
        jButtonexit1.setText("CLOSE");
        jButtonexit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonexit1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonexit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 446, 83, 43));

        deleteButton.setBackground(new java.awt.Color(228, 241, 254));
        deleteButton.setFont(new java.awt.Font("Gill Sans MT", 2, 18)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(34, 167, 240));
        deleteButton.setText("Delete");
        deleteButton.setEnabled(false);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 120, 40));

        editButton.setBackground(new java.awt.Color(228, 241, 254));
        editButton.setFont(new java.awt.Font("Gill Sans MT", 2, 18)); // NOI18N
        editButton.setForeground(new java.awt.Color(34, 167, 240));
        editButton.setText("Edit");
        editButton.setEnabled(false);
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        getContentPane().add(editButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 120, 40));

        newButton.setBackground(new java.awt.Color(228, 241, 254));
        newButton.setFont(new java.awt.Font("Gill Sans MT", 2, 18)); // NOI18N
        newButton.setForeground(new java.awt.Color(34, 167, 240));
        newButton.setText("New");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });
        getContentPane().add(newButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 120, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void proccessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proccessButtonActionPerformed
        AppointmentProccessForm ap = new AppointmentProccessForm(ids.get(selected_row), manager, this);
        ap.setTitle("HeXa Hospital Management System");
        ap.setSize(564, 620);
        ap.setLocationRelativeTo(null);
        ap.setVisible(true);          
    }//GEN-LAST:event_proccessButtonActionPerformed

    private void jButtonexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonexitActionPerformed
        Menu_Utama mu = new Menu_Utama();
        mu.setTitle("HeXa Hospital Management System");
        mu.setSize(800,540);
        mu.setLocationRelativeTo(null);
        mu.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        mu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonexitActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        selectRow(jTable1.getSelectedRow());
        if(manager.is_doctor() || manager.is_pharmacist()){
            proccessButton.setEnabled(true);
        }else{
            editButton.setEnabled(true);
            deleteButton.setEnabled(true);
        }
        System.out.println("Selected row "+jTable1.getSelectedRow());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonexit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonexit1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonexit1ActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog (null, "Are you sure want to delete this data?","Warning",dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION){
            manager.delete_appointment(ids.get(selected_row));
            refreshTable();
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        AppointmentForm ap = new AppointmentForm(ids.get(selected_row), manager, this);
        ap.setTitle("HeXa Hospital Management System");
        ap.setSize(564, 620);
        ap.setLocationRelativeTo(null);
        ap.setVisible(true);               // TODO add your handling code here:
    }//GEN-LAST:event_editButtonActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        AppointmentForm ap = new AppointmentForm(-1, manager, this);
        ap.setTitle("HeXa Hospital Management System");
        ap.setSize(564, 620);
        ap.setLocationRelativeTo(null);
        ap.setVisible(true);               // TODO add your handling code here:
    }//GEN-LAST:event_newButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Appointment a = new Appointment(null);
                a.setTitle("HeXa Hospital Management System");
                a.setSize(800,540);
                a.setLocationRelativeTo(null);
                a.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                a.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JButton jButtonexit;
    private javax.swing.JButton jButtonexit1;
    private javax.swing.JLabel jLabelhexa;
    private javax.swing.JPanel jPanelbiru;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton newButton;
    private javax.swing.JButton proccessButton;
    // End of variables declaration//GEN-END:variables

    private void selectRow(int selectedRow) {
        selected_row = selectedRow;
    }

    public void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        for (int i = model.getRowCount() - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        if(manager!=null){
            ArrayList<Object> appointment = manager.get_appointments(manager.is_doctor());
            
            ids.clear();
            for(int i=0; i<appointment.size(); i++){
                model.addRow((Object[]) appointment.get(i));
                Object id = (int)((Object[]) appointment.get(i))[0];
                ids.add((Integer) id);
            }  
        }else{
            model.addRow(new Object[]{"Column 1", "Column 2", "Column 3", "Column 4", "Column 5"});
        }
    }
}
