/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Rumah_Sakit;

import java.util.Arrays;
import javax.swing.JFrame;

public class MedicineForm extends javax.swing.JFrame {
    private DataManager manager;
    private int medicine_id;
    private Medicine parent = new Medicine(null);
    /**
     * Creates new form AdminForm
     */
    public MedicineForm(int user_id, DataManager manager, Medicine parent) {
        initComponents();
        initDatas(user_id, manager);
        this.parent = parent;
    }

    public void initDatas(int medicine_id, DataManager manager){       
        this.manager = manager;
        this.medicine_id = medicine_id;
        if(manager==null){
            jbuttonsave.setEnabled(false);
        }    
        
        if(medicine_id>=0 && manager!=null){
            Object[] medicine = manager.get_medicine(medicine_id);
            nameField.setText((String) medicine[1]);
            ingredientsField.setText((String) medicine[2]);
            effectsField.setText((String) medicine[3]);
            best_forField.setText((String) medicine[4]);
            priceField.setText((String) medicine[5]);
            stockField.setText((String) medicine [6]);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stockField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanelbiru = new javax.swing.JPanel();
        jLabelhexa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbuttonclose = new javax.swing.JButton();
        jbuttonsave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ingredientsField = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        effectsField = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        best_forField = new javax.swing.JTextArea();
        priceField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        stockField.setName("nameField"); // NOI18N
        stockField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockFieldActionPerformed(evt);
            }
        });
        getContentPane().add(stockField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 100, 100));

        jLabel8.setText("Stock :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 294, -1, 30));

        jPanelbiru.setBackground(new java.awt.Color(34, 167, 240));

        jLabelhexa.setBackground(new java.awt.Color(228, 241, 254));
        jLabelhexa.setFont(new java.awt.Font("Trajan Pro", 0, 24)); // NOI18N
        jLabelhexa.setForeground(new java.awt.Color(240, 240, 240));
        jLabelhexa.setText("ADD MEDICINE HEXA HOSPITAL");

        javax.swing.GroupLayout jPanelbiruLayout = new javax.swing.GroupLayout(jPanelbiru);
        jPanelbiru.setLayout(jPanelbiruLayout);
        jPanelbiruLayout.setHorizontalGroup(
            jPanelbiruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelbiruLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelhexa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelbiruLayout.setVerticalGroup(
            jPanelbiruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelbiruLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabelhexa, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        getContentPane().add(jPanelbiru, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 16, 450, -1));

        jLabel1.setText("Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        nameField.setName("nameField"); // NOI18N
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 250, 30));

        jLabel2.setText("Price:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, -1));

        jLabel3.setText("Ingredients:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 176, -1, -1));

        jbuttonclose.setBackground(new java.awt.Color(228, 241, 254));
        jbuttonclose.setFont(new java.awt.Font("Gill Sans MT", 2, 18)); // NOI18N
        jbuttonclose.setForeground(new java.awt.Color(34, 167, 240));
        jbuttonclose.setText("Close");
        jbuttonclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttoncloseActionPerformed(evt);
            }
        });
        getContentPane().add(jbuttonclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 120, 40));

        jbuttonsave.setBackground(new java.awt.Color(228, 241, 254));
        jbuttonsave.setFont(new java.awt.Font("Gill Sans MT", 2, 18)); // NOI18N
        jbuttonsave.setForeground(new java.awt.Color(34, 167, 240));
        jbuttonsave.setText("Save");
        jbuttonsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonsaveActionPerformed(evt);
            }
        });
        getContentPane().add(jbuttonsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 120, 40));

        ingredientsField.setColumns(20);
        ingredientsField.setRows(5);
        jScrollPane1.setViewportView(ingredientsField);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 196, 260, 100));

        effectsField.setColumns(20);
        effectsField.setRows(5);
        jScrollPane2.setViewportView(effectsField);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 250, -1));

        jLabel4.setText("Effects:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        best_forField.setColumns(20);
        best_forField.setRows(5);
        jScrollPane3.setViewportView(best_forField);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 420, 100));

        priceField.setName("nameField"); // NOI18N
        priceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceFieldActionPerformed(evt);
            }
        });
        getContentPane().add(priceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 250, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\hospital-master\\src\\Rumah_Sakit\\assets\\Hospital-compress2.png")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        jLabel7.setText("Used for:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rumah_Sakit/assets/Background fix.jpg"))); // NOI18N
        jLabel5.setText("Used for:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void jbuttoncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttoncloseActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jbuttoncloseActionPerformed

    private void jbuttonsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonsaveActionPerformed
        // TODO add your handling code here:
        String name = nameField.getText();
        String ingredients = ingredientsField.getText();
        String effects = effectsField.getText();
        String best_for = best_forField.getText();
        String price = priceField.getText();
        String stock = stockField.getText();
        String data[] = {name, ingredients, effects, best_for, price, stock};
        
        manager.save_medicine(medicine_id, data);
        parent.refreshTable();
        dispose();
    }//GEN-LAST:event_jbuttonsaveActionPerformed

    private void priceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceFieldActionPerformed

    private void stockFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MedicineForm af = new MedicineForm(-1, null, new Medicine(null));
                af.setTitle("HeXa Hospital Management System");
                af.setSize(564, 620);
                af.setLocationRelativeTo(null);
                af.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                af.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea best_forField;
    private javax.swing.JTextArea effectsField;
    private javax.swing.JTextArea ingredientsField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelhexa;
    private javax.swing.JPanel jPanelbiru;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbuttonclose;
    private javax.swing.JButton jbuttonsave;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField priceField;
    private javax.swing.JTextField stockField;
    // End of variables declaration//GEN-END:variables
}
