/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Rumah_Sakit;

import java.util.Arrays;
import javax.swing.JFrame;


public class PatientForm extends javax.swing.JFrame {
    private DataManager manager;
    private int patient_id;
    private Patient parent = new Patient(null);
    /**
     * Creates new form AdminForm
     */
    public PatientForm(int patient_id, DataManager manager, Patient parent) {
        initComponents();
        initDatas(patient_id, manager);
        this.parent = parent;
    }

    public void initDatas(int patient_id, DataManager manager){       
        this.manager = manager;
        this.patient_id = patient_id;
        if(manager==null){
            jbuttonadmin1.setEnabled(false);
        }    
        
        if(patient_id>=0 && manager!=null){
            Object[] patient = manager.get_patient(patient_id);
            nameField.setText((String) patient[1]);
            addressField.setText((String) patient[2]);
            ageField.setText((String) patient[3]);
            allergyField.setText((String) patient[5]);
            
            String[] gender_choiceIds = new String[genderChoice.getItemCount()];
            for(int i=0; i<genderChoice.getItemCount(); i++){
                gender_choiceIds[i] = genderChoice.getItemAt(i).toLowerCase();
            }
            genderChoice.setSelectedIndex(Arrays.asList(gender_choiceIds).indexOf(patient[4]));
            
            String[] bloodtype_choiceIds = new String[blood_typeChoice.getItemCount()];
            for(int i=0; i<blood_typeChoice.getItemCount(); i++){
                bloodtype_choiceIds[i] = blood_typeChoice.getItemAt(i).toLowerCase();
            }
            blood_typeChoice.setSelectedIndex(Arrays.asList(bloodtype_choiceIds).indexOf(patient[6]));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jPanelbiru = new javax.swing.JPanel();
        jLabelhexa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbuttonadmin2 = new javax.swing.JButton();
        jbuttonadmin1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressField = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        allergyField = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        ageField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        genderChoice = new javax.swing.JComboBox<>();
        blood_typeChoice = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\hospital-master\\src\\Rumah_Sakit\\assets\\Hospital-compress2.png")); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        jPanelbiru.setBackground(new java.awt.Color(34, 167, 240));

        jLabelhexa.setBackground(new java.awt.Color(228, 241, 254));
        jLabelhexa.setFont(new java.awt.Font("Trajan Pro", 0, 24)); // NOI18N
        jLabelhexa.setForeground(new java.awt.Color(240, 240, 240));
        jLabelhexa.setText("ADD PATIENT HEXA HOSPITAL");

        javax.swing.GroupLayout jPanelbiruLayout = new javax.swing.GroupLayout(jPanelbiru);
        jPanelbiru.setLayout(jPanelbiruLayout);
        jPanelbiruLayout.setHorizontalGroup(
            jPanelbiruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelbiruLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabelhexa, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanelbiruLayout.setVerticalGroup(
            jPanelbiruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelhexa, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelbiru, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, 16, 460, -1));

        jLabel1.setText("Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        nameField.setName("nameField"); // NOI18N
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 265, 40));

        jLabel2.setText("Age:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        jLabel3.setText("Address:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jbuttonadmin2.setBackground(new java.awt.Color(242, 38, 19));
        jbuttonadmin2.setFont(new java.awt.Font("Gill Sans MT", 2, 18)); // NOI18N
        jbuttonadmin2.setForeground(new java.awt.Color(255, 255, 255));
        jbuttonadmin2.setText("Close");
        jbuttonadmin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonadmin2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbuttonadmin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 120, 40));

        jbuttonadmin1.setBackground(new java.awt.Color(34, 167, 240));
        jbuttonadmin1.setFont(new java.awt.Font("Gill Sans MT", 2, 18)); // NOI18N
        jbuttonadmin1.setForeground(new java.awt.Color(255, 255, 255));
        jbuttonadmin1.setText("Save");
        jbuttonadmin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonadmin1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbuttonadmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 120, 40));

        addressField.setColumns(20);
        addressField.setRows(5);
        jScrollPane1.setViewportView(addressField);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 530, -1));

        allergyField.setColumns(20);
        allergyField.setRows(5);
        jScrollPane3.setViewportView(allergyField);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 410, 100));

        jLabel5.setText("Complaint :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        ageField.setName("nameField"); // NOI18N
        ageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageFieldActionPerformed(evt);
            }
        });
        getContentPane().add(ageField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 250, 40));

        jLabel4.setText("Gender:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        genderChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        getContentPane().add(genderChoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 100, -1));

        blood_typeChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "AB", "B", "O" }));
        getContentPane().add(blood_typeChoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 100, -1));

        jLabel6.setText("Blood Type:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rumah_Sakit/assets/Background fix.jpg"))); // NOI18N
        jLabel7.setText("Blood Type:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void jbuttonadmin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonadmin2ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jbuttonadmin2ActionPerformed

    private void jbuttonadmin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonadmin1ActionPerformed
        // TODO add your handling code here:
        String name = nameField.getText();
        String address = addressField.getText();
        String age = ageField.getText();
        String gender = genderChoice.getSelectedItem().toString().toLowerCase();
        String allergy = allergyField.getText();
        String blood_type = blood_typeChoice.getSelectedItem().toString().toLowerCase();
        String data[] = {name, address, age, gender, allergy, blood_type};
        
        manager.save_patient(patient_id, data);
        parent.refreshTable();
        dispose();
    }//GEN-LAST:event_jbuttonadmin1ActionPerformed

    private void ageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PatientForm af = new PatientForm(-1, null, new Patient(null));
                af.setTitle("HeXa Hospital Management System");
                af.setSize(564, 620);
                af.setLocationRelativeTo(null);
                af.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                af.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addressField;
    private javax.swing.JTextField ageField;
    private javax.swing.JTextArea allergyField;
    private javax.swing.JComboBox<String> blood_typeChoice;
    private javax.swing.JComboBox<String> genderChoice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelhexa;
    private javax.swing.JPanel jPanelbiru;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbuttonadmin1;
    private javax.swing.JButton jbuttonadmin2;
    private javax.swing.JTextField nameField;
    // End of variables declaration//GEN-END:variables
}
